# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

image:  ngqhung0912/java19-maven3.8.7-monocle

stages:
  - build
  - test
  - report
  - visualize

variables:
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -Dgitlab-ci=true -DIS_COMPILE_PANGO=true  -DtrimStackTrace=false"

  
modelTest-job:
  tags:
    - pppp
  stage: test
  script:
    - cd Azul/Model
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
  artifacts:
    paths:
      - Azul/Model/target/site/jacoco/jacoco.xml
    when: always
    reports:
      junit:
        - Azul/Model/target/surefire-reports/TEST-*.xml

viewTest-job:
 tags:
   - pppp
 stage: test
 script:
   - cd Azul/Model
   - mvn clean install
   - cd ../Controller
   - mvn clean install
   - cd ../View
   - mvn dependency:tree
   - mvn verify $MAVEN_CLI_OPTS
 artifacts:
   when: always
   reports:
     junit:
       - Azul/View/target/surefire-reports/TEST-*.xml

# deploy-prod:
#   image: alpine
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

sigridci:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  tags:
    - pppp

  script:
    - sigridci.py --customer utst --system P42023T14 --source . 
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    reports:
      junit: "sigrid-ci-output/sigridci-junit-format-report.xml"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_MERGE_REQUEST_ID
    
sigridpublish:
  stage: report
  image:
    name: softwareimprovementgroup/sigridci
  tags:
    - pppp

  script:
    - sigridci.py --customer utst --system P42023T14 --source . --publish
  allow_failure: true
  artifacts:
    paths:
      - "sigrid-ci-output/*"
    expire_in: 1 week
    when: always
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

coverage-job:
  # Must be in a stage later than test-jdk11's stage.
  # The `visualize` stage does not exist by default.
  # Please define it first, or choose an existing stage like `deploy`.
  stage: visualize
  coverage:  "/Total.*?([0-9]{1,3})%/"
  image: haynes/jacoco2cobertura:1.0.7
  script:
    # convert report from jacoco to cobertura, using relative project path
    - python3 /opt/cover2cover.py Azul/Model/target/site/jacoco/jacoco.xml /Azul/Model/src/main/java/ > cobertura-coverage.xml
  needs: ["modelTest-job"]
  dependencies:
    - "modelTest-job"
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: cobertura-coverage.xml




