# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

build-job:
  tags:
    - pppp
  image: openjdk:17
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "The University has general runners that will execute the pipeline available, but you must specify which docker image it needs to use as the environment to run in."
    - echo "See https://hub.docker.com/ for a listing of available images"

modelTest-job:
  tags:
    - pppp
  image: maven
  stage: test
  script:
    - cd Azul/Model
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - Azul/Model/target/surefire-reports/TEST-*.xml

viewTest-job:
  tags:
    - pppp
  image: maven
  stage: test
  script:
    - cd Azul/View
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - Azul/View/target/surefire-reports/TEST-*.xml

# deploy-prod:
#   image: alpine
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."




